# Generated by Django 4.1.1 on 2022-09-08 12:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resource.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_subject_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50, null=True)),
                ('publication', models.CharField(max_length=100, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to=resource.models.path_and_rename, validators=[resource.models.validate_file_extension])),
                ('resource_link', models.CharField(blank=True, max_length=200, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('term_no', models.CharField(max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('degree_categaroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.degree_categaroy')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.graduation')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='general.subject_assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_link', models.CharField(max_length=100)),
                ('chapter_no', models.IntegerField()),
                ('learning_style', models.CharField(choices=[('', 'Choose Learning Style'), ('V', 'Visual'), ('A', 'Auditory'), ('K', 'Kinaesthetic')], default='V', max_length=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
            ],
        ),
        migrations.CreateModel(
            name='School_Resource_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree_Categaroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.degree_categaroy')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('post_body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField(null=True)),
                ('degree_categaroy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.degree_categaroy')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.graduation')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.post_category')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='general.subject_assignment')),
            ],
        ),
    ]
