# Generated by Django 4.1.1 on 2022-09-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_subject_assignment'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_Resource_Map',
            new_name='college_Resource_Map',
        ),
    ]
