# Generated by Django 4.1.1 on 2022-09-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_subject_assignment'),
        ('resource', '0002_rename_school_resource_map_college_resource_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_resource_map',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.programme'),
        ),
        migrations.AddField(
            model_name='post',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.programme'),
        ),
        migrations.AddField(
            model_name='resource',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.programme'),
        ),
    ]
