# Generated by Django 4.1.1 on 2022-09-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_subject_assignment_options_and_more'),
        ('resource', '0003_college_resource_map_programme_post_programme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='subjects',
            new_name='subject_assignment',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='degree_categaroy',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='programme',
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ManyToManyField(related_name='re_subject', to='general.subject_assignment'),
        ),
    ]
