# Generated by Django 4.1.1 on 2022-09-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0006_portal_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_day_update', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.faculty_subject_assignment')),
            ],
            options={
                'verbose_name_plural': 'Log Book',
            },
        ),
        migrations.CreateModel(
            name='Log_Book_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(choices=[('', 'Choose hour'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1)),
                ('chapter', models.CharField(max_length=300)),
                ('content_delivered', models.TextField(max_length=300)),
                ('activity', models.TextField(max_length=300)),
                ('log_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.log_book')),
            ],
            options={
                'ordering': ('hour',),
            },
        ),
    ]
