# Generated by Django 4.1.1 on 2022-09-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subjects',
        ),
    ]
