# Generated by Django 4.1.1 on 2022-09-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Test'},
        ),
    ]
