# Generated by Django 4.1.1 on 2022-09-16 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import virtual_class.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_alter_subject_assignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('marks', models.IntegerField()),
                ('afile', models.FileField(null=True, upload_to=virtual_class.models.afile_path_and_rename, verbose_name='Assignment File')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('activate', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_assignment', models.ManyToManyField(to='general.subject_assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('croom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255, verbose_name='Video Link')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('link', models.URLField()),
                ('password_if_any', models.CharField(blank=True, max_length=30, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.classroom')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('marks', models.IntegerField()),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('R', 'Resend'), ('A', 'Accepted')], max_length=1)),
                ('sfile', models.FileField(null=True, upload_to=virtual_class.models.sfile_path_and_rename, verbose_name='Submission File')),
                ('corrected_answer_sheet', models.FileField(blank=True, null=True, upload_to='corrected_answer_sheet')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.assignment')),
                ('subject_assignment', models.ManyToManyField(to='general.subject_assignment')),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.forum')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('material', models.FileField(upload_to=virtual_class.models.path_and_rename)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.topic')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.topic'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_class.topic'),
        ),
    ]
