# Generated by Django 4.1.1 on 2022-09-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_portal_usage'),
        ('virtual_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.student'),
        ),
    ]
