# Generated by Django 4.1.1 on 2022-09-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_portal_usage'),
        ('virtual_class', '0002_submission_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject_assignment',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.subject_assignment'),
        ),
    ]
