# Generated by Django 4.1.1 on 2022-12-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_chapter'),
        ('virtual_class', '0003_remove_classroom_subject_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='croom',
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.chapter'),
        ),
    ]
