# Generated by Django 4.1.4 on 2022-12-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_chapter'),
        ('virtual_class', '0004_remove_topic_croom_topic_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='faculty_subject_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.faculty_subject_assignment'),
        ),
    ]
