# Generated by Django 4.1.4 on 2022-12-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_class', '0006_alter_assignment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='afile',
            field=models.FileField(null=True, upload_to='assignment', verbose_name='Assignment File'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sfile',
            field=models.FileField(null=True, upload_to='submission', verbose_name='Submission File'),
        ),
    ]
