# Generated by Django 4.1.4 on 2022-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_class', '0007_alter_assignment_afile_alter_submission_sfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='visible_to',
            field=models.CharField(choices=[('A', 'Student & Teacher'), ('S', 'Student')], default='A', max_length=1),
        ),
    ]
