# Generated by Django 4.1.1 on 2022-09-08 05:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acadmic_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), general.models.max_value_current_year], verbose_name='year')),
                ('end_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), general.models.max_value_current_year], verbose_name='year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Categaroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('degree_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.degree_categaroy')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('', 'Choose Graduation'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('Phd', 'Phd')], max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.graduation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=15)),
                ('year', models.CharField(choices=[('', 'Choose Year'), ('1', 'I - Year'), ('2', 'II - Year'), ('3', 'III - Year'), ('4', 'IV - Year'), ('5', 'V - Year')], max_length=2)),
                ('semester', models.CharField(choices=[('', 'Choose Semester'), ('1', 'I - Semester'), ('2', 'II - Semester'), ('3', 'III - Semester'), ('4', 'IV - Semester'), ('5', 'V - Semester'), ('6', 'VI - Semester'), ('7', 'VII - Semester'), ('8', 'VIII - Semester')], max_length=5)),
                ('dob', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('gender', models.CharField(choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('dor', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acadmic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.acadmic_year')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.district')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.state'),
        ),
    ]
