# Generated by Django 4.1.1 on 2022-09-08 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='end_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), general.models.max_value_current_year], verbose_name='End year'),
        ),
        migrations.AlterField(
            model_name='acadmic_year',
            name='start_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), general.models.max_value_current_year], verbose_name='start year'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('degree_categaroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.degree_categaroy')),
                ('subject_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.subject_category')),
            ],
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('urlload', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.student')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('dor', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acadmic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.acadmic_year')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.degree_categaroy')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.district')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.graduation')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
