# Generated by Django 4.1.1 on 2022-09-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_subject_category_alter_acadmic_year_end_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('', 'Choose Year'), ('1', 'I - Year'), ('2', 'II - Year'), ('3', 'III - Year'), ('4', 'IV - Year'), ('5', 'V - Year')], max_length=2)),
                ('semester', models.CharField(choices=[('', 'Choose Semester'), ('1', 'I - Semester'), ('2', 'II - Semester'), ('3', 'III - Semester'), ('4', 'IV - Semester'), ('5', 'V - Semester'), ('6', 'VI - Semester'), ('7', 'VII - Semester'), ('8', 'VIII - Semester')], max_length=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.department')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.graduation')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.programme')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.subject')),
            ],
            options={
                'ordering': ('subject__subject_title', 'graduation__code', 'department__short_name', 'programme__title'),
            },
        ),
    ]
