# Generated by Django 4.1.1 on 2022-09-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_subject_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_assignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='subject_assignment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject_assignment',
            name='graduation',
        ),
    ]
