# Generated by Django 4.1.1 on 2022-09-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_subject_assignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Subject_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='general.subject_assignment')),
            ],
        ),
    ]
