# Generated by Django 4.1.1 on 2022-09-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_portal_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subject_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.subject_category'),
        ),
    ]
