# Generated by Django 4.1.1 on 2022-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_assignment',
            name='section',
            field=models.CharField(choices=[('', 'Choose Section'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1, null=True),
        ),
    ]
