# Generated by Django 4.1.1 on 2022-11-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_remove_subject_assignment_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
