# Generated by Django 4.1.1 on 2022-12-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_faculty_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.subject_assignment')),
            ],
        ),
    ]
